import { 
  Category, Brand, Unit, Item, Supplier, Sale, Purchase, StockTransaction, Expense, StoreSettings 
} from '../types';

export const initialUnits: Unit[] = [
  { id: 'u_kg', name: 'Kilogram', short_code: 'KG', quantity_type: 'decimal', active: true },
  { id: 'u_g', name: 'Gram', short_code: 'G', quantity_type: 'decimal', active: true },
  { id: 'u_l', name: 'Liter', short_code: 'L', quantity_type: 'decimal', active: true },
  { id: 'u_ml', name: 'Milliliter', short_code: 'ML', quantity_type: 'decimal', active: true },
  { id: 'u_pcs', name: 'Pieces', short_code: 'PCS', quantity_type: 'integer', active: true },
  { id: 'u_pkt', name: 'Packet', short_code: 'PKT', quantity_type: 'integer', active: true },
  { id: 'u_pack', name: 'Pack', short_code: 'PACK', quantity_type: 'integer', active: true },
  { id: 'u_box', name: 'Box', short_code: 'BOX', quantity_type: 'integer', active: true },
  { id: 'u_bag', name: 'Bag', short_code: 'BAG', quantity_type: 'integer', active: true },
  { id: 'u_bottle', name: 'Bottle', short_code: 'BOTTLE', quantity_type: 'integer', active: true },
  { id: 'u_can', name: 'Can', short_code: 'CAN', quantity_type: 'integer', active: true },
  { id: 'u_tin', name: 'Tin', short_code: 'TIN', quantity_type: 'integer', active: true },
  { id: 'u_dzn', name: 'Dozen', short_code: 'DOZEN', quantity_type: 'integer', active: true },
  { id: 'u_pair', name: 'Pair', short_code: 'PAIR', quantity_type: 'integer', active: true },
];

export const initialCategories: Category[] = [
  { id: 'cat_grains', name: 'Rice & Grains', tamil_name: 'அரிசி & தானியங்கள்', active: true },
  { id: 'cat_dals', name: 'Dals & Pulses', tamil_name: 'பருப்பு வகைகள்', active: true },
  { id: 'cat_oils', name: 'Edible Oils & Ghee', tamil_name: 'சமையல் எண்ணெய் & நெய்', active: true },
  { id: 'cat_spices', name: 'Spices & Masala', tamil_name: 'மசாலா & மளிகை', active: true },
  { id: 'cat_veg', name: 'Fresh Vegetables', tamil_name: 'காய்கறிகள்', active: true },
  { id: 'cat_fruits', name: 'Fresh Fruits', tamil_name: 'பழங்கள்', active: true },
  { id: 'cat_dairy', name: 'Dairy & Milk', tamil_name: 'பால் & தயிர்', active: true },
  { id: 'cat_snacks', name: 'Snacks & Biscuits', tamil_name: 'தின்பண்டங்கள்', active: true },
  { id: 'cat_cleaning', name: 'Soaps & Household', tamil_name: 'சோப் & இல்லப் பொருட்கள்', active: true },
];

export const initialBrands: Brand[] = [
  { id: 'br_aashirvaad', name: 'Aashirvaad', active: true },
  { id: 'br_tata', name: 'Tata', active: true },
  { id: 'br_aachi', name: 'Aachi', active: true },
  { id: 'br_goldwinner', name: 'Gold Winner', active: true },
  { id: 'br_aavin', name: 'Aavin', active: true },
  { id: 'br_britannia', name: 'Britannia', active: true },
  { id: 'br_surf', name: 'Surf Excel', active: true },
  { id: 'br_local', name: 'Local Farm Fresh', active: true },
];

export const initialItems: Item[] = [
  {
    id: 'item_1',
    short_name: 'Ponni Boiled Rice 1kg',
    tamil_name: 'பொன்னி புழுங்கல் அரிசி',
    category_id: 'cat_grains',
    brand_id: 'br_local',
    unit_id: 'u_kg',
    barcode: '890103001',
    purchase_price: 48,
    sales_price: 58,
    mrp: 64,
    opening_stock: 250,
    current_stock: 210,
    min_stock: 50,
    gst_rate: 0,
    hsn_code: '1006',
    batch_enabled: false,
    active: true,
  },
  {
    id: 'item_2',
    short_name: 'Toor Dal Premium 1kg',
    tamil_name: 'துவரம் பருப்பு பிரீமியம்',
    category_id: 'cat_dals',
    brand_id: 'br_tata',
    unit_id: 'u_kg',
    barcode: '890103002',
    purchase_price: 125,
    sales_price: 148,
    mrp: 165,
    opening_stock: 90,
    current_stock: 65,
    min_stock: 25,
    gst_rate: 5,
    hsn_code: '0713',
    batch_enabled: true,
    batches: [
      {
        id: 'b_1',
        item_id: 'item_2',
        batch_no: 'TD-2026-03',
        manufacturing_date: '2026-08-10',
        expiry_date: '2027-02-10',
        quantity: 65,
        purchase_price: 125
      }
    ],
    active: true,
  },
  {
    id: 'item_3',
    short_name: 'Gold Winner Refined Oil 1L',
    tamil_name: 'கோல்ட் வின்னர் சூரியகாந்தி எண்ணெய் 1லி',
    category_id: 'cat_oils',
    brand_id: 'br_goldwinner',
    unit_id: 'u_pack',
    barcode: '890103003',
    purchase_price: 112,
    sales_price: 130,
    mrp: 145,
    opening_stock: 60,
    current_stock: 38,
    min_stock: 15,
    gst_rate: 5,
    hsn_code: '1512',
    batch_enabled: true,
    batches: [
      {
        id: 'b_2',
        item_id: 'item_3',
        batch_no: 'GW-OIL-88',
        manufacturing_date: '2026-07-01',
        expiry_date: '2027-01-01',
        quantity: 38,
        purchase_price: 112
      }
    ],
    active: true,
  },
  {
    id: 'item_4',
    short_name: 'Country Small Onion (Sambar Vengayam)',
    tamil_name: 'சின்ன வெங்காயம்',
    category_id: 'cat_veg',
    brand_id: 'br_local',
    unit_id: 'u_kg',
    barcode: '890103004',
    purchase_price: 42,
    sales_price: 56,
    mrp: 65,
    opening_stock: 45,
    current_stock: 28.5,
    min_stock: 10,
    gst_rate: 0,
    hsn_code: '0703',
    batch_enabled: false,
    active: true,
  },
  {
    id: 'item_5',
    short_name: 'Country Tomato 1kg',
    tamil_name: 'நாட்டு தக்காளி',
    category_id: 'cat_veg',
    brand_id: 'br_local',
    unit_id: 'u_kg',
    barcode: '890103005',
    purchase_price: 24,
    sales_price: 34,
    mrp: 40,
    opening_stock: 30,
    current_stock: 4.5, // Low stock trigger!
    min_stock: 12,
    gst_rate: 0,
    hsn_code: '0702',
    batch_enabled: false,
    active: true,
  },
  {
    id: 'item_6',
    short_name: 'Aachi Sambar Masala 100g',
    tamil_name: 'ஆச்சி சாம்பார் மசாலா 100கி',
    category_id: 'cat_spices',
    brand_id: 'br_aachi',
    unit_id: 'u_pkt',
    barcode: '890103006',
    purchase_price: 27,
    sales_price: 35,
    mrp: 38,
    opening_stock: 75,
    current_stock: 52,
    min_stock: 20,
    gst_rate: 12,
    hsn_code: '0910',
    batch_enabled: true,
    batches: [
      {
        id: 'b_3',
        item_id: 'item_6',
        batch_no: 'AC-SAM-09',
        manufacturing_date: '2026-05-15',
        expiry_date: '2026-11-15', // Expiring in ~1 month!
        quantity: 52,
        purchase_price: 27
      }
    ],
    active: true,
  },
  {
    id: 'item_7',
    short_name: 'Tata Salt Iodized 1kg',
    tamil_name: 'டாடா அயோடின் உப்பு 1கிலோ',
    category_id: 'cat_spices',
    brand_id: 'br_tata',
    unit_id: 'u_pkt',
    barcode: '890103007',
    purchase_price: 20,
    sales_price: 28,
    mrp: 30,
    opening_stock: 80,
    current_stock: 64,
    min_stock: 20,
    gst_rate: 0,
    hsn_code: '2501',
    batch_enabled: false,
    active: true,
  },
  {
    id: 'item_8',
    short_name: 'Aashirvaad Shudh Chakki Atta 5kg',
    tamil_name: 'ஆசிர்வாத் கோதுமை மாவு 5கிலோ',
    category_id: 'cat_grains',
    brand_id: 'br_aashirvaad',
    unit_id: 'u_bag',
    barcode: '890103008',
    purchase_price: 242,
    sales_price: 285,
    mrp: 310,
    opening_stock: 25,
    current_stock: 14,
    min_stock: 6,
    gst_rate: 5,
    hsn_code: '1101',
    batch_enabled: true,
    batches: [
      {
        id: 'b_4',
        item_id: 'item_8',
        batch_no: 'ASH-ATTA-5K',
        manufacturing_date: '2026-08-01',
        expiry_date: '2027-01-30',
        quantity: 14,
        purchase_price: 242
      }
    ],
    active: true,
  },
  {
    id: 'item_9',
    short_name: 'Aavin Fresh Milk 500ml',
    tamil_name: 'ஆவின் பசும்பால் 500மி.லி',
    category_id: 'cat_dairy',
    brand_id: 'br_aavin',
    unit_id: 'u_pkt',
    barcode: '890103009',
    purchase_price: 21,
    sales_price: 25,
    mrp: 25,
    opening_stock: 40,
    current_stock: 18,
    min_stock: 10,
    gst_rate: 0,
    hsn_code: '0401',
    batch_enabled: true,
    batches: [
      {
        id: 'b_5',
        item_id: 'item_9',
        batch_no: 'AV-DAIRY-04',
        manufacturing_date: '2026-10-03',
        expiry_date: '2026-10-06', // Fast expiry!
        quantity: 18,
        purchase_price: 21
      }
    ],
    active: true,
  },
  {
    id: 'item_10',
    short_name: 'Yellow Cavendish Banana',
    tamil_name: 'மஞ்சள் வாழைப்பழம் (டஜன்)',
    category_id: 'cat_fruits',
    brand_id: 'br_local',
    unit_id: 'u_dzn',
    barcode: '890103010',
    purchase_price: 36,
    sales_price: 52,
    mrp: 60,
    opening_stock: 20,
    current_stock: 9,
    min_stock: 5,
    gst_rate: 0,
    hsn_code: '0803',
    batch_enabled: false,
    active: true,
  },
  {
    id: 'item_11',
    short_name: 'Britannia Marie Gold 300g',
    tamil_name: 'பிரிட்டானியா மேரி கோல்ட் பிஸ்கட்',
    category_id: 'cat_snacks',
    brand_id: 'br_britannia',
    unit_id: 'u_pack',
    barcode: '890103011',
    purchase_price: 30,
    sales_price: 38,
    mrp: 42,
    opening_stock: 50,
    current_stock: 36,
    min_stock: 15,
    gst_rate: 18,
    hsn_code: '1905',
    batch_enabled: true,
    batches: [
      {
        id: 'b_6',
        item_id: 'item_11',
        batch_no: 'BR-MARIE-99',
        manufacturing_date: '2026-07-20',
        expiry_date: '2027-03-20',
        quantity: 36,
        purchase_price: 30
      }
    ],
    active: true,
  },
  {
    id: 'item_12',
    short_name: 'Surf Excel Detergent Bar 250g',
    tamil_name: 'சர்ப் எக்செல் பார் சோப்',
    category_id: 'cat_cleaning',
    brand_id: 'br_surf',
    unit_id: 'u_pcs',
    barcode: '890103012',
    purchase_price: 25,
    sales_price: 32,
    mrp: 35,
    opening_stock: 45,
    current_stock: 2, // Low stock critical!
    min_stock: 12,
    gst_rate: 18,
    hsn_code: '3401',
    batch_enabled: false,
    active: true,
  },
  {
    id: 'item_13',
    short_name: 'Fresh Coconut Polished',
    tamil_name: 'நடுத்தர தேங்காய்',
    category_id: 'cat_veg',
    brand_id: 'br_local',
    unit_id: 'u_pcs',
    barcode: '890103013',
    purchase_price: 22,
    sales_price: 32,
    mrp: 38,
    opening_stock: 100,
    current_stock: 68,
    min_stock: 25,
    gst_rate: 0,
    hsn_code: '0801',
    batch_enabled: false,
    active: true,
  },
  {
    id: 'item_14',
    short_name: 'Mustard Seeds / Kadugu 100g',
    tamil_name: 'நாட்டு கடுகு 100கி',
    category_id: 'cat_spices',
    brand_id: 'br_local',
    unit_id: 'u_pkt',
    barcode: '890103014',
    purchase_price: 13,
    sales_price: 20,
    mrp: 24,
    opening_stock: 60,
    current_stock: 42,
    min_stock: 15,
    gst_rate: 5,
    hsn_code: '0910',
    batch_enabled: false,
    active: true,
  }
];

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup_1',
    name: 'Madurai Wholesale Provisions Co.',
    phone: '9842109876',
    address: '42 South Masi Street, Madurai, TN',
    gstin: '33AABCT1234F1Z8',
  },
  {
    id: 'sup_2',
    name: 'Lakshmi Agro & Grain Millers',
    phone: '9443217654',
    address: '18 Rice Mill Road, Trichy, TN',
    gstin: '33AABCL5678K1Z3',
  },
  {
    id: 'sup_3',
    name: 'Kaveri Farm Fresh Veggies',
    phone: '9789012345',
    address: 'Gandhi Market, Tiruchirappalli, TN',
    gstin: '33AAECK9988P1Z1',
  },
];

export const initialSales: Sale[] = [
  {
    id: 'sale_1',
    invoice_no: 'INV-2026-0038',
    customer_id: 'cust_walkin',
    customer_name: 'Walk-in Customer (சில்லறை)',
    date: '2026-10-04 10:15',
    subtotal: 356,
    discount: 10,
    tax: 9.8,
    round_off: 0.2,
    total: 356,
    total_cost: 285,
    gross_profit: 61.2,
    payment_method: 'Cash',
    received: 500,
    balance: 144,
    status: 'Completed',
    lines: [
      {
        id: 'sl_1',
        sale_id: 'sale_1',
        item_id: 'item_1',
        item_name_en: 'Ponni Boiled Rice 1kg',
        item_name_ta: 'பொன்னி புழுங்கல் அரிசி',
        unit: 'KG',
        quantity_type: 'decimal',
        quantity: 2,
        unit_price: 58,
        cost_price: 48,
        discount: 0,
        gst_rate: 0,
        tax_amount: 0,
        amount: 116,
      },
      {
        id: 'sl_2',
        sale_id: 'sale_1',
        item_id: 'item_2',
        item_name_en: 'Toor Dal Premium 1kg',
        item_name_ta: 'துவரம் பருப்பு பிரீமியம்',
        unit: 'KG',
        quantity_type: 'decimal',
        quantity: 1,
        unit_price: 148,
        cost_price: 125,
        discount: 0,
        gst_rate: 5,
        tax_amount: 7.4,
        amount: 148,
      },
      {
        id: 'sl_3',
        sale_id: 'sale_1',
        item_id: 'item_4',
        item_name_en: 'Country Small Onion (Sambar Vengayam)',
        item_name_ta: 'சின்ன வெங்காயம்',
        unit: 'KG',
        quantity_type: 'decimal',
        quantity: 1.5,
        unit_price: 56,
        cost_price: 42,
        discount: 0,
        gst_rate: 0,
        tax_amount: 0,
        amount: 84,
      }
    ]
  },
  {
    id: 'sale_2',
    invoice_no: 'INV-2026-0039',
    customer_id: 'cust_walkin',
    customer_name: 'Walk-in Customer (சில்லறை)',
    date: '2026-10-04 11:42',
    subtotal: 540,
    discount: 20,
    tax: 15.5,
    round_off: -0.5,
    total: 535,
    total_cost: 410,
    gross_profit: 109.5,
    payment_method: 'UPI',
    received: 535,
    balance: 0,
    status: 'Completed',
    lines: [
      {
        id: 'sl_4',
        sale_id: 'sale_2',
        item_id: 'item_3',
        item_name_en: 'Gold Winner Refined Oil 1L',
        item_name_ta: 'கோல்ட் வின்னர் சூரியகாந்தி எண்ணெய் 1லி',
        unit: 'PACK',
        quantity_type: 'integer',
        quantity: 2,
        unit_price: 130,
        cost_price: 112,
        discount: 0,
        gst_rate: 5,
        tax_amount: 13,
        amount: 260,
      },
      {
        id: 'sl_5',
        sale_id: 'sale_2',
        item_id: 'item_8',
        item_name_en: 'Aashirvaad Shudh Chakki Atta 5kg',
        item_name_ta: 'ஆசிர்வாத் கோதுமை மாவு 5கிலோ',
        unit: 'BAG',
        quantity_type: 'integer',
        quantity: 1,
        unit_price: 285,
        cost_price: 242,
        discount: 0,
        gst_rate: 5,
        tax_amount: 14.25,
        amount: 285,
      }
    ]
  }
];

export const initialPurchases: Purchase[] = [
  {
    id: 'pur_1',
    invoice_no: 'PUR-8821',
    supplier_id: 'sup_1',
    supplier_name: 'Madurai Wholesale Provisions Co.',
    date: '2026-10-02 09:30',
    subtotal: 8400,
    discount: 200,
    tax: 380,
    total: 8580,
    payment_method: 'Bank Transfer',
    lines: [
      {
        id: 'pl_1',
        purchase_id: 'pur_1',
        item_id: 'item_1',
        item_name_en: 'Ponni Boiled Rice 1kg',
        item_name_ta: 'பொன்னி புழுங்கல் அரிசி',
        unit: 'KG',
        quantity: 100,
        purchase_price: 48,
        gst_rate: 0,
        tax_amount: 0,
        amount: 4800,
      },
      {
        id: 'pl_2',
        purchase_id: 'pur_1',
        item_id: 'item_2',
        item_name_en: 'Toor Dal Premium 1kg',
        item_name_ta: 'துவரம் பருப்பு பிரீமியம்',
        unit: 'KG',
        quantity: 30,
        purchase_price: 120,
        gst_rate: 5,
        tax_amount: 180,
        amount: 3600,
        batch_no: 'TD-2026-03',
        expiry_date: '2027-02-10'
      }
    ]
  }
];

export const initialExpenses: Expense[] = [
  {
    id: 'exp_1',
    category: 'Electricity',
    description: 'TNEB Commercial Power Bill September',
    amount: 1450,
    date: '2026-10-01',
    payment_method: 'UPI',
  },
  {
    id: 'exp_2',
    category: 'Tea & Snacks',
    description: 'Shop Staff Morning & Evening Tea',
    amount: 180,
    date: '2026-10-04',
    payment_method: 'Cash',
  }
];

export const initialStockTransactions: StockTransaction[] = [
  {
    id: 'tx_1',
    item_id: 'item_1',
    type: 'OPENING',
    reference_id: 'INITIAL-STOCK',
    quantity_delta: 250,
    unit_cost: 48,
    date: '2026-10-01 08:00',
    notes: 'Initial inventory count'
  },
  {
    id: 'tx_2',
    item_id: 'item_1',
    type: 'SALE',
    reference_id: 'INV-2026-0038',
    quantity_delta: -2,
    unit_cost: 48,
    date: '2026-10-04 10:15',
    notes: 'POS Sale Walk-in Customer'
  }
];

export const initialSettings: StoreSettings = {
  store_name: 'Sri Murugan Super Market',
  store_name_ta: 'ஸ்ரீ முருகன் சூப்பர் மார்க்கெட்',
  tagline: 'Fresh Provisions, Groceries & Daily Needs',
  address: 'No. 24, Gandhi Road, Opp. Bus Stand, Madurai - 625001',
  phone: '+91 98421 98765 / 0452-254321',
  email: 'contact@muruganstores.in',
  gstin: '33AABCS8899Q1Z4',
  invoice_prefix: 'INV-2026-',
  next_invoice_number: 40,
  default_payment_method: 'Cash',
  enable_round_off: true,
  printer_type: 'thermal_80mm',
  receipt_footer_note: 'Thank you for shopping with us! Visit again. / நல்வரவு வாழ்த்துகள்!',
  currency_symbol: '₹',
};
